
from core.domotica_exception import DomoticaException

class ConfiguratorException(DomoticaException):
    pass
