from core.domotica_exception import DomoticaException

class EventException(DomoticaException):
    pass
