from core.domotica_exception import DomoticaException

class ActionException(DomoticaException):
    pass
