
from core.domotica_exception import DomoticaException

class ExecuterCoreException(DomoticaException):
    pass
