from core.domotica_exception import DomoticaException

class ClientCoreException(DomoticaException):
    pass
